fix log hint messages (#84)
Remove an unnecessary HINT message.

For example, when we try to create IMMV with array_agg(), the following error
is raised. The hint doesn't make sense because array_agg is a  built-in aggregate.

 CREATE INCREMENTAL MATERIALIZED VIEW  mv_ivm16 AS SELECT array_agg(j) FROM mv_base_a;
 ERROR:  aggregate function array_agg(anynonarray) is not supported             
 HINT:  IVM supports only built-in aggregate functions.