Improve an error message for unspoorted aggregate functions
Currentlly only built-in aggregate functions are supported, so
aggregates on user-defined types causes an error at view definition
time. However, the message was unappropreate like:

 ERROR:  aggregate function max is not supported

even though built-in max is supported. Therefore, this is improved
to include its argument types as following:

 ERROR:  aggregate function min(xxx) is not supported
 HINT:  IVM supports only built-in aggregate functions.

(Github issue #65)