Fix a build error due to fmgrtab.c (#56)
Gen_fmgrtab.pl was broken and caused a make error as following:
 error: ‘aggregate_dummy’ undeclared here (not in a function)